[versions]
agp = "8.13.2"
kotlin = "2.2.21"
androidx-nav3 = "1.0.0"
androidx-lifecycle = "2.10.0"
hilt = "2.57.2"
retrofit = "3.0.0"

[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.17.0"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.2.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.12.1"
androidx-compose-bom = "androidx.compose:compose-bom:2025.12.00"
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-material3 = "androidx.compose.material3:material3:1.5.0-alpha10"
androidx-compose-material3-windowsizeclass = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-graphics-shapes = "androidx.graphics:graphics-shapes:1.1.0"
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "androidx-nav3" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "androidx-nav3" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-lifecycle-viewmodel-compose = "androidx.hilt:hilt-lifecycle-viewmodel-compose:1.3.0"
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp = "com.squareup.okhttp3:okhttp:5.3.2"
coil-compose = "io.coil-kt:coil-compose:2.7.0"
lazycolumn-scrollbar = "com.github.nanihadesuka:LazyColumnScrollbar:2.2.0"
material-motion-compose-core = "io.github.fornewid:material-motion-compose-core:2.0.1"
android-tools-sdk-common = "com.android.tools:sdk-common:31.13.2"
dom4j = "org.dom4j:dom4j:2.2.0"
commons-io = "commons-io:commons-io:2.21.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = "com.google.devtools.ksp:2.3.3"
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
licensee = "app.cash.licensee:1.14.1"
spotless = "com.diffplug.spotless:8.1.0"
