[versions]
androidxCore = "1.17.0"
androidxCoreSplashscreen = "1.2.0"
androidxActivity = "1.12.1"
androidxComposeBom = "2025.12.00"
androidxComposeMaterial3 = "1.5.0-alpha10"
androidxGraphicsShapes = "1.1.0"
androidxNavigation3 = "1.0.0"
androidxLifecycle = "2.10.0"
kotlinxSerializationJson = "1.9.0"
hilt = "2.57.2"
hiltLifecycleViewModelCompose = "1.3.0"
retrofit = "3.0.0"
okhttp = "5.3.2"
coil = "2.7.0"
lazyColumnScrollbar = "2.2.0"
materialMotionCompose = "2.0.1"
androidApplication = "8.13.2"
kotlin = "2.2.21"
ksp = "2.3.3"
licensee = "1.14.1"
spotless = "8.1.0"
androidToolsSdkCommon = "31.13.2"
dom4j = "2.2.0"
commonsIo = "2.21.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-material3-windowsizeclass = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-graphics-shapes = { module = "androidx.graphics:graphics-shapes", version.ref = "androidxGraphicsShapes" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "androidxNavigation3" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "androidxNavigation3" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-lifecycle-viewmodel-compose = { module = "androidx.hilt:hilt-lifecycle-viewmodel-compose", version.ref = "hiltLifecycleViewModelCompose" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
lazycolumn-scrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "lazyColumnScrollbar" }
material-motion-compose-core = { module = "io.github.fornewid:material-motion-compose-core", version.ref = "materialMotionCompose" }
android-tools-sdk-common = { module = "com.android.tools:sdk-common", version.ref = "androidToolsSdkCommon" }
dom4j = { module = "org.dom4j:dom4j", version.ref = "dom4j" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplication" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
licensee = { id = "app.cash.licensee", version.ref = "licensee" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
# no need to provide version
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm" }
