blank_issues_enabled: false
contact_links:
  - name: Link apps and icons
    url: https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#adding-icons-and-missing-app-components-to-lawnicons
    about: Learn more about linking an app to an existing icon via a pull request.
  - name: Icon requests (suspended)
    url: https://forms.gle/nR4ozeeJBKrLwGfk6
    about: Consider contributing.
